%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: ./USdeathprobabilities_1997-2018.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 26-Nov-2021 21:31:47

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 22);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "B4:W104";

% Specify column names and types
opts.VariableNames = ["year1997", "year1998", "year1999", "year2000", "year2001", "year2002", "year2003", "year2004", "year2005", "year2006", "year2007", "year2008", "year2009", "year2010", "year2011", "year2012", "year2013", "year2014", "year2015", "year2016", "year2017", "year2018"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
USdeathprobabilities1997to2018table = readtable("./USdeathprobabilities_1997-2018.xlsx", opts, "UseExcel", false);

%% Convert to output type
USdeathprobabilities1997to2018 = table2array(USdeathprobabilities1997to2018table);

%% Clear temporary variables
clear opts